//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CPP14.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CPP14Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface ICPP14Visitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.translationunit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTranslationunit([NotNull] CPP14Parser.TranslationunitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.primaryexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryexpression([NotNull] CPP14Parser.PrimaryexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.idexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdexpression([NotNull] CPP14Parser.IdexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.unqualifiedid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnqualifiedid([NotNull] CPP14Parser.UnqualifiedidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.qualifiedid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedid([NotNull] CPP14Parser.QualifiedidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.nestednamespecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNestednamespecifier([NotNull] CPP14Parser.NestednamespecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.lambdaexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaexpression([NotNull] CPP14Parser.LambdaexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.lambdaintroducer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaintroducer([NotNull] CPP14Parser.LambdaintroducerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.lambdacapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdacapture([NotNull] CPP14Parser.LambdacaptureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.capturedefault"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCapturedefault([NotNull] CPP14Parser.CapturedefaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.capturelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCapturelist([NotNull] CPP14Parser.CapturelistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.capture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCapture([NotNull] CPP14Parser.CaptureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.simplecapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimplecapture([NotNull] CPP14Parser.SimplecaptureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.initcapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitcapture([NotNull] CPP14Parser.InitcaptureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.lambdadeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdadeclarator([NotNull] CPP14Parser.LambdadeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.postfixexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfixexpression([NotNull] CPP14Parser.PostfixexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.expressionlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionlist([NotNull] CPP14Parser.ExpressionlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.pseudodestructorname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPseudodestructorname([NotNull] CPP14Parser.PseudodestructornameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.unaryexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryexpression([NotNull] CPP14Parser.UnaryexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.unaryoperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryoperator([NotNull] CPP14Parser.UnaryoperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.newexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewexpression([NotNull] CPP14Parser.NewexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.newplacement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewplacement([NotNull] CPP14Parser.NewplacementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.newtypeid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewtypeid([NotNull] CPP14Parser.NewtypeidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.newdeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewdeclarator([NotNull] CPP14Parser.NewdeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.noptrnewdeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoptrnewdeclarator([NotNull] CPP14Parser.NoptrnewdeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.newinitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewinitializer([NotNull] CPP14Parser.NewinitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.deleteexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeleteexpression([NotNull] CPP14Parser.DeleteexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.noexceptexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoexceptexpression([NotNull] CPP14Parser.NoexceptexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.castexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCastexpression([NotNull] CPP14Parser.CastexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.pmexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPmexpression([NotNull] CPP14Parser.PmexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.multiplicativeexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeexpression([NotNull] CPP14Parser.MultiplicativeexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.additiveexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveexpression([NotNull] CPP14Parser.AdditiveexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.shiftexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShiftexpression([NotNull] CPP14Parser.ShiftexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.relationalexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalexpression([NotNull] CPP14Parser.RelationalexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.equalityexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualityexpression([NotNull] CPP14Parser.EqualityexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.andexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndexpression([NotNull] CPP14Parser.AndexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.exclusiveorexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExclusiveorexpression([NotNull] CPP14Parser.ExclusiveorexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.inclusiveorexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInclusiveorexpression([NotNull] CPP14Parser.InclusiveorexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.logicalandexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalandexpression([NotNull] CPP14Parser.LogicalandexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.logicalorexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalorexpression([NotNull] CPP14Parser.LogicalorexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.conditionalexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalexpression([NotNull] CPP14Parser.ConditionalexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.assignmentexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentexpression([NotNull] CPP14Parser.AssignmentexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.assignmentoperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentoperator([NotNull] CPP14Parser.AssignmentoperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] CPP14Parser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.constantexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantexpression([NotNull] CPP14Parser.ConstantexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] CPP14Parser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.labeledstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabeledstatement([NotNull] CPP14Parser.LabeledstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.expressionstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionstatement([NotNull] CPP14Parser.ExpressionstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.compoundstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompoundstatement([NotNull] CPP14Parser.CompoundstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.statementseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementseq([NotNull] CPP14Parser.StatementseqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.selectionstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectionstatement([NotNull] CPP14Parser.SelectionstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] CPP14Parser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.iterationstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIterationstatement([NotNull] CPP14Parser.IterationstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.forinitstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForinitstatement([NotNull] CPP14Parser.ForinitstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.forrangedeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForrangedeclaration([NotNull] CPP14Parser.ForrangedeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.forrangeinitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForrangeinitializer([NotNull] CPP14Parser.ForrangeinitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.jumpstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJumpstatement([NotNull] CPP14Parser.JumpstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.declarationstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationstatement([NotNull] CPP14Parser.DeclarationstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.declarationseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationseq([NotNull] CPP14Parser.DeclarationseqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] CPP14Parser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.blockdeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockdeclaration([NotNull] CPP14Parser.BlockdeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.aliasdeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAliasdeclaration([NotNull] CPP14Parser.AliasdeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.simpledeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpledeclaration([NotNull] CPP14Parser.SimpledeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.static_assertdeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatic_assertdeclaration([NotNull] CPP14Parser.Static_assertdeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.emptydeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptydeclaration([NotNull] CPP14Parser.EmptydeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.attributedeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributedeclaration([NotNull] CPP14Parser.AttributedeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.declspecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclspecifier([NotNull] CPP14Parser.DeclspecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.declspecifierseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclspecifierseq([NotNull] CPP14Parser.DeclspecifierseqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.storageclassspecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStorageclassspecifier([NotNull] CPP14Parser.StorageclassspecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.functionspecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionspecifier([NotNull] CPP14Parser.FunctionspecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.typedefname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypedefname([NotNull] CPP14Parser.TypedefnameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.typespecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypespecifier([NotNull] CPP14Parser.TypespecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.trailingtypespecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrailingtypespecifier([NotNull] CPP14Parser.TrailingtypespecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.typespecifierseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypespecifierseq([NotNull] CPP14Parser.TypespecifierseqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.trailingtypespecifierseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrailingtypespecifierseq([NotNull] CPP14Parser.TrailingtypespecifierseqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.simpletypespecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpletypespecifier([NotNull] CPP14Parser.SimpletypespecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.thetypename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThetypename([NotNull] CPP14Parser.ThetypenameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.decltypespecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecltypespecifier([NotNull] CPP14Parser.DecltypespecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.elaboratedtypespecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElaboratedtypespecifier([NotNull] CPP14Parser.ElaboratedtypespecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.enumname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumname([NotNull] CPP14Parser.EnumnameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.enumspecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumspecifier([NotNull] CPP14Parser.EnumspecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.enumhead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumhead([NotNull] CPP14Parser.EnumheadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.opaqueenumdeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpaqueenumdeclaration([NotNull] CPP14Parser.OpaqueenumdeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.enumkey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumkey([NotNull] CPP14Parser.EnumkeyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.enumbase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumbase([NotNull] CPP14Parser.EnumbaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.enumeratorlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumeratorlist([NotNull] CPP14Parser.EnumeratorlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.enumeratordefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumeratordefinition([NotNull] CPP14Parser.EnumeratordefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.enumerator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerator([NotNull] CPP14Parser.EnumeratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.namespacename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespacename([NotNull] CPP14Parser.NamespacenameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.originalnamespacename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOriginalnamespacename([NotNull] CPP14Parser.OriginalnamespacenameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.namespacedefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespacedefinition([NotNull] CPP14Parser.NamespacedefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.namednamespacedefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamednamespacedefinition([NotNull] CPP14Parser.NamednamespacedefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.originalnamespacedefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOriginalnamespacedefinition([NotNull] CPP14Parser.OriginalnamespacedefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.extensionnamespacedefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtensionnamespacedefinition([NotNull] CPP14Parser.ExtensionnamespacedefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.unnamednamespacedefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnnamednamespacedefinition([NotNull] CPP14Parser.UnnamednamespacedefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.namespacebody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespacebody([NotNull] CPP14Parser.NamespacebodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.namespacealias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespacealias([NotNull] CPP14Parser.NamespacealiasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.namespacealiasdefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespacealiasdefinition([NotNull] CPP14Parser.NamespacealiasdefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.qualifiednamespacespecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiednamespacespecifier([NotNull] CPP14Parser.QualifiednamespacespecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.usingdeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingdeclaration([NotNull] CPP14Parser.UsingdeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.usingdirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingdirective([NotNull] CPP14Parser.UsingdirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.asmdefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsmdefinition([NotNull] CPP14Parser.AsmdefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.linkagespecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLinkagespecification([NotNull] CPP14Parser.LinkagespecificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.attributespecifierseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributespecifierseq([NotNull] CPP14Parser.AttributespecifierseqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.attributespecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributespecifier([NotNull] CPP14Parser.AttributespecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.alignmentspecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlignmentspecifier([NotNull] CPP14Parser.AlignmentspecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.attributelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributelist([NotNull] CPP14Parser.AttributelistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] CPP14Parser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.attributetoken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributetoken([NotNull] CPP14Parser.AttributetokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.attributescopedtoken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributescopedtoken([NotNull] CPP14Parser.AttributescopedtokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.attributenamespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributenamespace([NotNull] CPP14Parser.AttributenamespaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.attributeargumentclause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeargumentclause([NotNull] CPP14Parser.AttributeargumentclauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.balancedtokenseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBalancedtokenseq([NotNull] CPP14Parser.BalancedtokenseqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.balancedtoken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBalancedtoken([NotNull] CPP14Parser.BalancedtokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.initdeclaratorlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitdeclaratorlist([NotNull] CPP14Parser.InitdeclaratorlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.initdeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitdeclarator([NotNull] CPP14Parser.InitdeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarator([NotNull] CPP14Parser.DeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.ptrdeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPtrdeclarator([NotNull] CPP14Parser.PtrdeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.noptrdeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoptrdeclarator([NotNull] CPP14Parser.NoptrdeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.parametersandqualifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParametersandqualifiers([NotNull] CPP14Parser.ParametersandqualifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.trailingreturntype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrailingreturntype([NotNull] CPP14Parser.TrailingreturntypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.ptroperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPtroperator([NotNull] CPP14Parser.PtroperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.cvqualifierseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCvqualifierseq([NotNull] CPP14Parser.CvqualifierseqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.cvqualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCvqualifier([NotNull] CPP14Parser.CvqualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.refqualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRefqualifier([NotNull] CPP14Parser.RefqualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.declaratorid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaratorid([NotNull] CPP14Parser.DeclaratoridContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.thetypeid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThetypeid([NotNull] CPP14Parser.ThetypeidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.abstractdeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbstractdeclarator([NotNull] CPP14Parser.AbstractdeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.ptrabstractdeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPtrabstractdeclarator([NotNull] CPP14Parser.PtrabstractdeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.noptrabstractdeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoptrabstractdeclarator([NotNull] CPP14Parser.NoptrabstractdeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.abstractpackdeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbstractpackdeclarator([NotNull] CPP14Parser.AbstractpackdeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.noptrabstractpackdeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoptrabstractpackdeclarator([NotNull] CPP14Parser.NoptrabstractpackdeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.parameterdeclarationclause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterdeclarationclause([NotNull] CPP14Parser.ParameterdeclarationclauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.parameterdeclarationlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterdeclarationlist([NotNull] CPP14Parser.ParameterdeclarationlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.parameterdeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterdeclaration([NotNull] CPP14Parser.ParameterdeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.functiondefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctiondefinition([NotNull] CPP14Parser.FunctiondefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.udefineTopLevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUdefineTopLevel([NotNull] CPP14Parser.UdefineTopLevelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.udefine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUdefine([NotNull] CPP14Parser.UdefineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.uclass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUclass([NotNull] CPP14Parser.UclassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.ustruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUstruct([NotNull] CPP14Parser.UstructContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.uenum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUenum([NotNull] CPP14Parser.UenumContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.ufunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUfunction([NotNull] CPP14Parser.UfunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.uproperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUproperty([NotNull] CPP14Parser.UpropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.udeprecated"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUdeprecated([NotNull] CPP14Parser.UdeprecatedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.umeta"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUmeta([NotNull] CPP14Parser.UmetaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.umetaParametrList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUmetaParametrList([NotNull] CPP14Parser.UmetaParametrListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.umetaParametr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUmetaParametr([NotNull] CPP14Parser.UmetaParametrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.umetaParametrKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUmetaParametrKey([NotNull] CPP14Parser.UmetaParametrKeyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.umetaParametrValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUmetaParametrValue([NotNull] CPP14Parser.UmetaParametrValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.functionbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionbody([NotNull] CPP14Parser.FunctionbodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializer([NotNull] CPP14Parser.InitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.braceorequalinitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBraceorequalinitializer([NotNull] CPP14Parser.BraceorequalinitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.initializerclause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializerclause([NotNull] CPP14Parser.InitializerclauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.initializerlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializerlist([NotNull] CPP14Parser.InitializerlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.bracedinitlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracedinitlist([NotNull] CPP14Parser.BracedinitlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.classname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassname([NotNull] CPP14Parser.ClassnameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.classspecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassspecifier([NotNull] CPP14Parser.ClassspecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.classhead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClasshead([NotNull] CPP14Parser.ClassheadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.classheadname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassheadname([NotNull] CPP14Parser.ClassheadnameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.classUEAPI"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassUEAPI([NotNull] CPP14Parser.ClassUEAPIContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.classvirtspecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassvirtspecifier([NotNull] CPP14Parser.ClassvirtspecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.classkey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClasskey([NotNull] CPP14Parser.ClasskeyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.memberspecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberspecification([NotNull] CPP14Parser.MemberspecificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.memberdeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberdeclaration([NotNull] CPP14Parser.MemberdeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.memberdeclaratorlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberdeclaratorlist([NotNull] CPP14Parser.MemberdeclaratorlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.memberdeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberdeclarator([NotNull] CPP14Parser.MemberdeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.virtspecifierseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVirtspecifierseq([NotNull] CPP14Parser.VirtspecifierseqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.virtspecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVirtspecifier([NotNull] CPP14Parser.VirtspecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.purespecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPurespecifier([NotNull] CPP14Parser.PurespecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.baseclause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseclause([NotNull] CPP14Parser.BaseclauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.basespecifierlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBasespecifierlist([NotNull] CPP14Parser.BasespecifierlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.basespecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBasespecifier([NotNull] CPP14Parser.BasespecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.classordecltype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassordecltype([NotNull] CPP14Parser.ClassordecltypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.basetypespecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBasetypespecifier([NotNull] CPP14Parser.BasetypespecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.accessspecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessspecifier([NotNull] CPP14Parser.AccessspecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.conversionfunctionid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConversionfunctionid([NotNull] CPP14Parser.ConversionfunctionidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.conversiontypeid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConversiontypeid([NotNull] CPP14Parser.ConversiontypeidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.conversiondeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConversiondeclarator([NotNull] CPP14Parser.ConversiondeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.ctorinitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCtorinitializer([NotNull] CPP14Parser.CtorinitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.meminitializerlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMeminitializerlist([NotNull] CPP14Parser.MeminitializerlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.meminitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMeminitializer([NotNull] CPP14Parser.MeminitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.meminitializerid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMeminitializerid([NotNull] CPP14Parser.MeminitializeridContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.operatorfunctionid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorfunctionid([NotNull] CPP14Parser.OperatorfunctionidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.literaloperatorid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteraloperatorid([NotNull] CPP14Parser.LiteraloperatoridContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.templatedeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplatedeclaration([NotNull] CPP14Parser.TemplatedeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.templateparameterlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateparameterlist([NotNull] CPP14Parser.TemplateparameterlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.templateparameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateparameter([NotNull] CPP14Parser.TemplateparameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.typeparameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeparameter([NotNull] CPP14Parser.TypeparameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.simpletemplateid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpletemplateid([NotNull] CPP14Parser.SimpletemplateidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.templateid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateid([NotNull] CPP14Parser.TemplateidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.templatename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplatename([NotNull] CPP14Parser.TemplatenameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.templateargumentlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateargumentlist([NotNull] CPP14Parser.TemplateargumentlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.templateargument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateargument([NotNull] CPP14Parser.TemplateargumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.typenamespecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypenamespecifier([NotNull] CPP14Parser.TypenamespecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.explicitinstantiation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicitinstantiation([NotNull] CPP14Parser.ExplicitinstantiationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.explicitspecialization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicitspecialization([NotNull] CPP14Parser.ExplicitspecializationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.tryblock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTryblock([NotNull] CPP14Parser.TryblockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.functiontryblock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctiontryblock([NotNull] CPP14Parser.FunctiontryblockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.handlerseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHandlerseq([NotNull] CPP14Parser.HandlerseqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.handler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHandler([NotNull] CPP14Parser.HandlerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.exceptiondeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExceptiondeclaration([NotNull] CPP14Parser.ExceptiondeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.throwexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThrowexpression([NotNull] CPP14Parser.ThrowexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.exceptionspecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExceptionspecification([NotNull] CPP14Parser.ExceptionspecificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.dynamicexceptionspecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDynamicexceptionspecification([NotNull] CPP14Parser.DynamicexceptionspecificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.typeidlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeidlist([NotNull] CPP14Parser.TypeidlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.noexceptspecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoexceptspecification([NotNull] CPP14Parser.NoexceptspecificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.rightShift"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRightShift([NotNull] CPP14Parser.RightShiftContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.rightShiftAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRightShiftAssign([NotNull] CPP14Parser.RightShiftAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.theoperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTheoperator([NotNull] CPP14Parser.TheoperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] CPP14Parser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.booleanliteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanliteral([NotNull] CPP14Parser.BooleanliteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.pointerliteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointerliteral([NotNull] CPP14Parser.PointerliteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.userdefinedliteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUserdefinedliteral([NotNull] CPP14Parser.UserdefinedliteralContext context);
}
