//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from UHeader.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="UHeaderParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface IUHeaderVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.translationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTranslationUnit([NotNull] UHeaderParser.TranslationUnitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.topLevelOutClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTopLevelOutClass([NotNull] UHeaderParser.TopLevelOutClassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.topLevelInClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTopLevelInClass([NotNull] UHeaderParser.TopLevelInClassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.classPreDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassPreDeclaration([NotNull] UHeaderParser.ClassPreDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDeclaration([NotNull] UHeaderParser.ClassDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.classType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassType([NotNull] UHeaderParser.ClassTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.classParentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassParentList([NotNull] UHeaderParser.ClassParentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassName([NotNull] UHeaderParser.ClassNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassBody([NotNull] UHeaderParser.ClassBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.uDefine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUDefine([NotNull] UHeaderParser.UDefineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.uDefineName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUDefineName([NotNull] UHeaderParser.UDefineNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.uMeta"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUMeta([NotNull] UHeaderParser.UMetaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.uMetaParametrList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUMetaParametrList([NotNull] UHeaderParser.UMetaParametrListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.uMetaParametr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUMetaParametr([NotNull] UHeaderParser.UMetaParametrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.uMetaParamKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUMetaParamKey([NotNull] UHeaderParser.UMetaParamKeyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.uMetaParamValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUMetaParamValue([NotNull] UHeaderParser.UMetaParamValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod([NotNull] UHeaderParser.MethodContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.methodParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodParams([NotNull] UHeaderParser.MethodParamsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.methodParametr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodParametr([NotNull] UHeaderParser.MethodParametrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.methodParametrName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodParametrName([NotNull] UHeaderParser.MethodParametrNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.methodBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodBody([NotNull] UHeaderParser.MethodBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.methodBodyContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodBodyContent([NotNull] UHeaderParser.MethodBodyContentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.methodName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodName([NotNull] UHeaderParser.MethodNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] UHeaderParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.accessSpecifierContainer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessSpecifierContainer([NotNull] UHeaderParser.AccessSpecifierContainerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.accessSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessSpecifier([NotNull] UHeaderParser.AccessSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="UHeaderParser.preprocessDerective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreprocessDerective([NotNull] UHeaderParser.PreprocessDerectiveContext context);
}
